# Generated by Django 3.2.6 on 2021-08-15 23:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.IntegerField(unique=True, verbose_name='Pokemon id')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('experience', models.IntegerField(verbose_name='Experience')),
                ('height', models.IntegerField(verbose_name='Height')),
                ('is_default', models.BooleanField(verbose_name='Default?')),
                ('weight', models.IntegerField(verbose_name='Weight')),
                ('owner', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
